# Generated by Django 4.2.6 on 2024-06-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_name_meal_meal_time_meal_meal_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='meal_plan',
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_content',
            field=models.CharField(max_length=100),
        ),
    ]
